<?php
/**
 * BookingRentalCar
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightWrite
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BrightWrite™
 *
 * BrightWrite API
 *
 * OpenAPI spec version: 0.1.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BrightWrite\Model;

use \ArrayAccess;

/**
 * BookingRentalCar Class Doc Comment
 *
 * @category    Class */
/**
 * @package     BrightWrite
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BookingRentalCar implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'BookingRentalCar';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'totalPrice' => 'double',
        'dropOffLocation' => '\BrightWrite\Model\RentalCarLocation',
        'priceCurrency' => 'string',
        'pickupLocation' => '\BrightWrite\Model\RentalCarLocation',
        'taxesAndFees' => 'double',
        'subtotalPrice' => 'double',
        'pickupDateTime' => '\DateTime',
        'provider' => 'string',
        'dropOffDateTime' => '\DateTime',
        'toddlerSeatCount' => 'int',
        'driverCount' => 'int',
        'infantChildSeatCount' => 'int',
        'sIPPCode' => 'string',
        'rentalCarBookingID' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'totalPrice' => 'totalPrice',
        'dropOffLocation' => 'dropOffLocation',
        'priceCurrency' => 'priceCurrency',
        'pickupLocation' => 'pickupLocation',
        'taxesAndFees' => 'taxesAndFees',
        'subtotalPrice' => 'subtotalPrice',
        'pickupDateTime' => 'pickupDateTime',
        'provider' => 'provider',
        'dropOffDateTime' => 'dropOffDateTime',
        'toddlerSeatCount' => 'toddlerSeatCount',
        'driverCount' => 'driverCount',
        'infantChildSeatCount' => 'infantChildSeatCount',
        'sIPPCode' => 'SIPPCode',
        'rentalCarBookingID' => 'rentalCarBookingID'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'totalPrice' => 'setTotalPrice',
        'dropOffLocation' => 'setDropOffLocation',
        'priceCurrency' => 'setPriceCurrency',
        'pickupLocation' => 'setPickupLocation',
        'taxesAndFees' => 'setTaxesAndFees',
        'subtotalPrice' => 'setSubtotalPrice',
        'pickupDateTime' => 'setPickupDateTime',
        'provider' => 'setProvider',
        'dropOffDateTime' => 'setDropOffDateTime',
        'toddlerSeatCount' => 'setToddlerSeatCount',
        'driverCount' => 'setDriverCount',
        'infantChildSeatCount' => 'setInfantChildSeatCount',
        'sIPPCode' => 'setSIPPCode',
        'rentalCarBookingID' => 'setRentalCarBookingID'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'totalPrice' => 'getTotalPrice',
        'dropOffLocation' => 'getDropOffLocation',
        'priceCurrency' => 'getPriceCurrency',
        'pickupLocation' => 'getPickupLocation',
        'taxesAndFees' => 'getTaxesAndFees',
        'subtotalPrice' => 'getSubtotalPrice',
        'pickupDateTime' => 'getPickupDateTime',
        'provider' => 'getProvider',
        'dropOffDateTime' => 'getDropOffDateTime',
        'toddlerSeatCount' => 'getToddlerSeatCount',
        'driverCount' => 'getDriverCount',
        'infantChildSeatCount' => 'getInfantChildSeatCount',
        'sIPPCode' => 'getSIPPCode',
        'rentalCarBookingID' => 'getRentalCarBookingID'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['totalPrice'] = isset($data['totalPrice']) ? $data['totalPrice'] : null;
        $this->container['dropOffLocation'] = isset($data['dropOffLocation']) ? $data['dropOffLocation'] : null;
        $this->container['priceCurrency'] = isset($data['priceCurrency']) ? $data['priceCurrency'] : null;
        $this->container['pickupLocation'] = isset($data['pickupLocation']) ? $data['pickupLocation'] : null;
        $this->container['taxesAndFees'] = isset($data['taxesAndFees']) ? $data['taxesAndFees'] : null;
        $this->container['subtotalPrice'] = isset($data['subtotalPrice']) ? $data['subtotalPrice'] : null;
        $this->container['pickupDateTime'] = isset($data['pickupDateTime']) ? $data['pickupDateTime'] : null;
        $this->container['provider'] = isset($data['provider']) ? $data['provider'] : null;
        $this->container['dropOffDateTime'] = isset($data['dropOffDateTime']) ? $data['dropOffDateTime'] : null;
        $this->container['toddlerSeatCount'] = isset($data['toddlerSeatCount']) ? $data['toddlerSeatCount'] : null;
        $this->container['driverCount'] = isset($data['driverCount']) ? $data['driverCount'] : null;
        $this->container['infantChildSeatCount'] = isset($data['infantChildSeatCount']) ? $data['infantChildSeatCount'] : null;
        $this->container['sIPPCode'] = isset($data['sIPPCode']) ? $data['sIPPCode'] : null;
        $this->container['rentalCarBookingID'] = isset($data['rentalCarBookingID']) ? $data['rentalCarBookingID'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        if ($this->container['totalPrice'] === null) {
            $invalid_properties[] = "'totalPrice' can't be null";
        }
        if (($this->container['totalPrice'] > 100000.0)) {
            $invalid_properties[] = "invalid value for 'totalPrice', must be smaller than or equal to 100000.0.";
        }

        if (($this->container['totalPrice'] < 0.01)) {
            $invalid_properties[] = "invalid value for 'totalPrice', must be bigger than or equal to 0.01.";
        }

        if ($this->container['dropOffLocation'] === null) {
            $invalid_properties[] = "'dropOffLocation' can't be null";
        }
        if ($this->container['priceCurrency'] === null) {
            $invalid_properties[] = "'priceCurrency' can't be null";
        }
        if ((strlen($this->container['priceCurrency']) > 3)) {
            $invalid_properties[] = "invalid value for 'priceCurrency', the character length must be smaller than or equal to 3.";
        }

        if ((strlen($this->container['priceCurrency']) < 3)) {
            $invalid_properties[] = "invalid value for 'priceCurrency', the character length must be bigger than or equal to 3.";
        }

        if ($this->container['pickupLocation'] === null) {
            $invalid_properties[] = "'pickupLocation' can't be null";
        }
        if ($this->container['taxesAndFees'] === null) {
            $invalid_properties[] = "'taxesAndFees' can't be null";
        }
        if (($this->container['taxesAndFees'] > 100000.0)) {
            $invalid_properties[] = "invalid value for 'taxesAndFees', must be smaller than or equal to 100000.0.";
        }

        if (($this->container['taxesAndFees'] < 0.01)) {
            $invalid_properties[] = "invalid value for 'taxesAndFees', must be bigger than or equal to 0.01.";
        }

        if ($this->container['subtotalPrice'] === null) {
            $invalid_properties[] = "'subtotalPrice' can't be null";
        }
        if (($this->container['subtotalPrice'] > 100000.0)) {
            $invalid_properties[] = "invalid value for 'subtotalPrice', must be smaller than or equal to 100000.0.";
        }

        if (($this->container['subtotalPrice'] < 0.01)) {
            $invalid_properties[] = "invalid value for 'subtotalPrice', must be bigger than or equal to 0.01.";
        }

        if ($this->container['pickupDateTime'] === null) {
            $invalid_properties[] = "'pickupDateTime' can't be null";
        }
        if ($this->container['provider'] === null) {
            $invalid_properties[] = "'provider' can't be null";
        }
        if ((strlen($this->container['provider']) > 64)) {
            $invalid_properties[] = "invalid value for 'provider', the character length must be smaller than or equal to 64.";
        }

        if ((strlen($this->container['provider']) < 2)) {
            $invalid_properties[] = "invalid value for 'provider', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['dropOffDateTime'] === null) {
            $invalid_properties[] = "'dropOffDateTime' can't be null";
        }
        if (!is_null($this->container['toddlerSeatCount']) && ($this->container['toddlerSeatCount'] > 4)) {
            $invalid_properties[] = "invalid value for 'toddlerSeatCount', must be smaller than or equal to 4.";
        }

        if (!is_null($this->container['toddlerSeatCount']) && ($this->container['toddlerSeatCount'] < 0)) {
            $invalid_properties[] = "invalid value for 'toddlerSeatCount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['driverCount']) && ($this->container['driverCount'] > 4)) {
            $invalid_properties[] = "invalid value for 'driverCount', must be smaller than or equal to 4.";
        }

        if (!is_null($this->container['driverCount']) && ($this->container['driverCount'] < 0)) {
            $invalid_properties[] = "invalid value for 'driverCount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['infantChildSeatCount']) && ($this->container['infantChildSeatCount'] > 4)) {
            $invalid_properties[] = "invalid value for 'infantChildSeatCount', must be smaller than or equal to 4.";
        }

        if (!is_null($this->container['infantChildSeatCount']) && ($this->container['infantChildSeatCount'] < 0)) {
            $invalid_properties[] = "invalid value for 'infantChildSeatCount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['sIPPCode']) && (strlen($this->container['sIPPCode']) > 4)) {
            $invalid_properties[] = "invalid value for 'sIPPCode', the character length must be smaller than or equal to 4.";
        }

        if (!is_null($this->container['sIPPCode']) && (strlen($this->container['sIPPCode']) < 4)) {
            $invalid_properties[] = "invalid value for 'sIPPCode', the character length must be bigger than or equal to 4.";
        }

        if ($this->container['rentalCarBookingID'] === null) {
            $invalid_properties[] = "'rentalCarBookingID' can't be null";
        }
        if ((strlen($this->container['rentalCarBookingID']) > 64)) {
            $invalid_properties[] = "invalid value for 'rentalCarBookingID', the character length must be smaller than or equal to 64.";
        }

        if ((strlen($this->container['rentalCarBookingID']) < 1)) {
            $invalid_properties[] = "invalid value for 'rentalCarBookingID', the character length must be bigger than or equal to 1.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['totalPrice'] === null) {
            return false;
        }
        if ($this->container['totalPrice'] > 100000.0) {
            return false;
        }
        if ($this->container['totalPrice'] < 0.01) {
            return false;
        }
        if ($this->container['dropOffLocation'] === null) {
            return false;
        }
        if ($this->container['priceCurrency'] === null) {
            return false;
        }
        if (strlen($this->container['priceCurrency']) > 3) {
            return false;
        }
        if (strlen($this->container['priceCurrency']) < 3) {
            return false;
        }
        if ($this->container['pickupLocation'] === null) {
            return false;
        }
        if ($this->container['taxesAndFees'] === null) {
            return false;
        }
        if ($this->container['taxesAndFees'] > 100000.0) {
            return false;
        }
        if ($this->container['taxesAndFees'] < 0.01) {
            return false;
        }
        if ($this->container['subtotalPrice'] === null) {
            return false;
        }
        if ($this->container['subtotalPrice'] > 100000.0) {
            return false;
        }
        if ($this->container['subtotalPrice'] < 0.01) {
            return false;
        }
        if ($this->container['pickupDateTime'] === null) {
            return false;
        }
        if ($this->container['provider'] === null) {
            return false;
        }
        if (strlen($this->container['provider']) > 64) {
            return false;
        }
        if (strlen($this->container['provider']) < 2) {
            return false;
        }
        if ($this->container['dropOffDateTime'] === null) {
            return false;
        }
        if ($this->container['toddlerSeatCount'] > 4) {
            return false;
        }
        if ($this->container['toddlerSeatCount'] < 0) {
            return false;
        }
        if ($this->container['driverCount'] > 4) {
            return false;
        }
        if ($this->container['driverCount'] < 0) {
            return false;
        }
        if ($this->container['infantChildSeatCount'] > 4) {
            return false;
        }
        if ($this->container['infantChildSeatCount'] < 0) {
            return false;
        }
        if (strlen($this->container['sIPPCode']) > 4) {
            return false;
        }
        if (strlen($this->container['sIPPCode']) < 4) {
            return false;
        }
        if ($this->container['rentalCarBookingID'] === null) {
            return false;
        }
        if (strlen($this->container['rentalCarBookingID']) > 64) {
            return false;
        }
        if (strlen($this->container['rentalCarBookingID']) < 1) {
            return false;
        }
        return true;
    }


    /**
     * Gets totalPrice
     * @return double
     */
    public function getTotalPrice()
    {
        return $this->container['totalPrice'];
    }

    /**
     * Sets totalPrice
     * @param double $totalPrice Ticket price including taxes and extra fees. Should be equal to subtotalPrice + taxesAndFees.
     * @return $this
     */
    public function setTotalPrice($totalPrice)
    {

        if (($totalPrice > 100000.0)) {
            throw new \InvalidArgumentException('invalid value for $totalPrice when calling BookingRentalCar., must be smaller than or equal to 100000.0.');
        }
        if (($totalPrice < 0.01)) {
            throw new \InvalidArgumentException('invalid value for $totalPrice when calling BookingRentalCar., must be bigger than or equal to 0.01.');
        }

        $this->container['totalPrice'] = $totalPrice;

        return $this;
    }

    /**
     * Gets dropOffLocation
     * @return \BrightWrite\Model\RentalCarLocation
     */
    public function getDropOffLocation()
    {
        return $this->container['dropOffLocation'];
    }

    /**
     * Sets dropOffLocation
     * @param \BrightWrite\Model\RentalCarLocation $dropOffLocation
     * @return $this
     */
    public function setDropOffLocation($dropOffLocation)
    {
        $this->container['dropOffLocation'] = $dropOffLocation;

        return $this;
    }

    /**
     * Gets priceCurrency
     * @return string
     */
    public function getPriceCurrency()
    {
        return $this->container['priceCurrency'];
    }

    /**
     * Sets priceCurrency
     * @param string $priceCurrency Currency in which all pricing info is specified three letters code as described by ISO 4217.
     * @return $this
     */
    public function setPriceCurrency($priceCurrency)
    {
        if ((strlen($priceCurrency) > 3)) {
            throw new \InvalidArgumentException('invalid length for $priceCurrency when calling BookingRentalCar., must be smaller than or equal to 3.');
        }
        if ((strlen($priceCurrency) < 3)) {
            throw new \InvalidArgumentException('invalid length for $priceCurrency when calling BookingRentalCar., must be bigger than or equal to 3.');
        }

        $this->container['priceCurrency'] = $priceCurrency;

        return $this;
    }

    /**
     * Gets pickupLocation
     * @return \BrightWrite\Model\RentalCarLocation
     */
    public function getPickupLocation()
    {
        return $this->container['pickupLocation'];
    }

    /**
     * Sets pickupLocation
     * @param \BrightWrite\Model\RentalCarLocation $pickupLocation
     * @return $this
     */
    public function setPickupLocation($pickupLocation)
    {
        $this->container['pickupLocation'] = $pickupLocation;

        return $this;
    }

    /**
     * Gets taxesAndFees
     * @return double
     */
    public function getTaxesAndFees()
    {
        return $this->container['taxesAndFees'];
    }

    /**
     * Sets taxesAndFees
     * @param double $taxesAndFees Total of taxes, fees and other deductions required on top of the subtotalPrice.
     * @return $this
     */
    public function setTaxesAndFees($taxesAndFees)
    {

        if (($taxesAndFees > 100000.0)) {
            throw new \InvalidArgumentException('invalid value for $taxesAndFees when calling BookingRentalCar., must be smaller than or equal to 100000.0.');
        }
        if (($taxesAndFees < 0.01)) {
            throw new \InvalidArgumentException('invalid value for $taxesAndFees when calling BookingRentalCar., must be bigger than or equal to 0.01.');
        }

        $this->container['taxesAndFees'] = $taxesAndFees;

        return $this;
    }

    /**
     * Gets subtotalPrice
     * @return double
     */
    public function getSubtotalPrice()
    {
        return $this->container['subtotalPrice'];
    }

    /**
     * Sets subtotalPrice
     * @param double $subtotalPrice Ticket price without taxes and extra fees.
     * @return $this
     */
    public function setSubtotalPrice($subtotalPrice)
    {

        if (($subtotalPrice > 100000.0)) {
            throw new \InvalidArgumentException('invalid value for $subtotalPrice when calling BookingRentalCar., must be smaller than or equal to 100000.0.');
        }
        if (($subtotalPrice < 0.01)) {
            throw new \InvalidArgumentException('invalid value for $subtotalPrice when calling BookingRentalCar., must be bigger than or equal to 0.01.');
        }

        $this->container['subtotalPrice'] = $subtotalPrice;

        return $this;
    }

    /**
     * Gets pickupDateTime
     * @return \DateTime
     */
    public function getPickupDateTime()
    {
        return $this->container['pickupDateTime'];
    }

    /**
     * Sets pickupDateTime
     * @param \DateTime $pickupDateTime When the custmer is going to pick up the car.
     * @return $this
     */
    public function setPickupDateTime($pickupDateTime)
    {
        $this->container['pickupDateTime'] = $pickupDateTime;

        return $this;
    }

    /**
     * Gets provider
     * @return string
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     * @param string $provider Service provider, i.e. rental car agency.
     * @return $this
     */
    public function setProvider($provider)
    {
        if ((strlen($provider) > 64)) {
            throw new \InvalidArgumentException('invalid length for $provider when calling BookingRentalCar., must be smaller than or equal to 64.');
        }
        if ((strlen($provider) < 2)) {
            throw new \InvalidArgumentException('invalid length for $provider when calling BookingRentalCar., must be bigger than or equal to 2.');
        }

        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets dropOffDateTime
     * @return \DateTime
     */
    public function getDropOffDateTime()
    {
        return $this->container['dropOffDateTime'];
    }

    /**
     * Sets dropOffDateTime
     * @param \DateTime $dropOffDateTime When the custmer is going to return the car.
     * @return $this
     */
    public function setDropOffDateTime($dropOffDateTime)
    {
        $this->container['dropOffDateTime'] = $dropOffDateTime;

        return $this;
    }

    /**
     * Gets toddlerSeatCount
     * @return int
     */
    public function getToddlerSeatCount()
    {
        return $this->container['toddlerSeatCount'];
    }

    /**
     * Sets toddlerSeatCount
     * @param int $toddlerSeatCount How many toddler car seats are required.
     * @return $this
     */
    public function setToddlerSeatCount($toddlerSeatCount)
    {

        if (!is_null($toddlerSeatCount) && ($toddlerSeatCount > 4)) {
            throw new \InvalidArgumentException('invalid value for $toddlerSeatCount when calling BookingRentalCar., must be smaller than or equal to 4.');
        }
        if (!is_null($toddlerSeatCount) && ($toddlerSeatCount < 0)) {
            throw new \InvalidArgumentException('invalid value for $toddlerSeatCount when calling BookingRentalCar., must be bigger than or equal to 0.');
        }

        $this->container['toddlerSeatCount'] = $toddlerSeatCount;

        return $this;
    }

    /**
     * Gets driverCount
     * @return int
     */
    public function getDriverCount()
    {
        return $this->container['driverCount'];
    }

    /**
     * Sets driverCount
     * @param int $driverCount How many drivers are going to use the car.
     * @return $this
     */
    public function setDriverCount($driverCount)
    {

        if (!is_null($driverCount) && ($driverCount > 4)) {
            throw new \InvalidArgumentException('invalid value for $driverCount when calling BookingRentalCar., must be smaller than or equal to 4.');
        }
        if (!is_null($driverCount) && ($driverCount < 0)) {
            throw new \InvalidArgumentException('invalid value for $driverCount when calling BookingRentalCar., must be bigger than or equal to 0.');
        }

        $this->container['driverCount'] = $driverCount;

        return $this;
    }

    /**
     * Gets infantChildSeatCount
     * @return int
     */
    public function getInfantChildSeatCount()
    {
        return $this->container['infantChildSeatCount'];
    }

    /**
     * Sets infantChildSeatCount
     * @param int $infantChildSeatCount How many infant car seats are required.
     * @return $this
     */
    public function setInfantChildSeatCount($infantChildSeatCount)
    {

        if (!is_null($infantChildSeatCount) && ($infantChildSeatCount > 4)) {
            throw new \InvalidArgumentException('invalid value for $infantChildSeatCount when calling BookingRentalCar., must be smaller than or equal to 4.');
        }
        if (!is_null($infantChildSeatCount) && ($infantChildSeatCount < 0)) {
            throw new \InvalidArgumentException('invalid value for $infantChildSeatCount when calling BookingRentalCar., must be bigger than or equal to 0.');
        }

        $this->container['infantChildSeatCount'] = $infantChildSeatCount;

        return $this;
    }

    /**
     * Gets sIPPCode
     * @return string
     */
    public function getSIPPCode()
    {
        return $this->container['sIPPCode'];
    }

    /**
     * Sets sIPPCode
     * @param string $sIPPCode SIPP codes are used to summarise the key features of a vehicle.
     * @return $this
     */
    public function setSIPPCode($sIPPCode)
    {
        if (!is_null($sIPPCode) && (strlen($sIPPCode) > 4)) {
            throw new \InvalidArgumentException('invalid length for $sIPPCode when calling BookingRentalCar., must be smaller than or equal to 4.');
        }
        if (!is_null($sIPPCode) && (strlen($sIPPCode) < 4)) {
            throw new \InvalidArgumentException('invalid length for $sIPPCode when calling BookingRentalCar., must be bigger than or equal to 4.');
        }

        $this->container['sIPPCode'] = $sIPPCode;

        return $this;
    }

    /**
     * Gets rentalCarBookingID
     * @return string
     */
    public function getRentalCarBookingID()
    {
        return $this->container['rentalCarBookingID'];
    }

    /**
     * Sets rentalCarBookingID
     * @param string $rentalCarBookingID Internal ID used by distributors to identify the booking. This should match the booking ID BrightWrite collects from the tags on the distributor website. For a booking that has flights and rental cars, the booking IDs would match.
     * @return $this
     */
    public function setRentalCarBookingID($rentalCarBookingID)
    {
        if ((strlen($rentalCarBookingID) > 64)) {
            throw new \InvalidArgumentException('invalid length for $rentalCarBookingID when calling BookingRentalCar., must be smaller than or equal to 64.');
        }
        if ((strlen($rentalCarBookingID) < 1)) {
            throw new \InvalidArgumentException('invalid length for $rentalCarBookingID when calling BookingRentalCar., must be bigger than or equal to 1.');
        }

        $this->container['rentalCarBookingID'] = $rentalCarBookingID;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\BrightWrite\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\BrightWrite\ObjectSerializer::sanitizeForSerialization($this));
    }
}
