<?php
/**
 * RentalCarLocation
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightWrite
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BrightWrite™
 *
 * BrightWrite API
 *
 * OpenAPI spec version: 0.1.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BrightWrite\Model;

use \ArrayAccess;

/**
 * RentalCarLocation Class Doc Comment
 *
 * @category    Class */
/**
 * @package     BrightWrite
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RentalCarLocation implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RentalCarLocation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'city' => 'string',
        'state' => 'string',
        'branchName' => 'string',
        'country' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'city' => 'city',
        'state' => 'state',
        'branchName' => 'branchName',
        'country' => 'country'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'city' => 'setCity',
        'state' => 'setState',
        'branchName' => 'setBranchName',
        'country' => 'setCountry'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'city' => 'getCity',
        'state' => 'getState',
        'branchName' => 'getBranchName',
        'country' => 'getCountry'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['branchName'] = isset($data['branchName']) ? $data['branchName'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        if (!is_null($this->container['city']) && (strlen($this->container['city']) > 64)) {
            $invalid_properties[] = "invalid value for 'city', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['city']) && (strlen($this->container['city']) < 2)) {
            $invalid_properties[] = "invalid value for 'city', the character length must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['state']) && (strlen($this->container['state']) > 64)) {
            $invalid_properties[] = "invalid value for 'state', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['state']) && (strlen($this->container['state']) < 2)) {
            $invalid_properties[] = "invalid value for 'state', the character length must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['branchName']) && (strlen($this->container['branchName']) > 64)) {
            $invalid_properties[] = "invalid value for 'branchName', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['branchName']) && (strlen($this->container['branchName']) < 2)) {
            $invalid_properties[] = "invalid value for 'branchName', the character length must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['country']) && (strlen($this->container['country']) > 64)) {
            $invalid_properties[] = "invalid value for 'country', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['country']) && (strlen($this->container['country']) < 2)) {
            $invalid_properties[] = "invalid value for 'country', the character length must be bigger than or equal to 2.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if (strlen($this->container['city']) > 64) {
            return false;
        }
        if (strlen($this->container['city']) < 2) {
            return false;
        }
        if (strlen($this->container['state']) > 64) {
            return false;
        }
        if (strlen($this->container['state']) < 2) {
            return false;
        }
        if (strlen($this->container['branchName']) > 64) {
            return false;
        }
        if (strlen($this->container['branchName']) < 2) {
            return false;
        }
        if (strlen($this->container['country']) > 64) {
            return false;
        }
        if (strlen($this->container['country']) < 2) {
            return false;
        }
        return true;
    }


    /**
     * Gets city
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     * @param string $city City of the rental car company branch.
     * @return $this
     */
    public function setCity($city)
    {
        if (!is_null($city) && (strlen($city) > 64)) {
            throw new \InvalidArgumentException('invalid length for $city when calling RentalCarLocation., must be smaller than or equal to 64.');
        }
        if (!is_null($city) && (strlen($city) < 2)) {
            throw new \InvalidArgumentException('invalid length for $city when calling RentalCarLocation., must be bigger than or equal to 2.');
        }

        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     * @param string $state State in which the branch city is located.
     * @return $this
     */
    public function setState($state)
    {
        if (!is_null($state) && (strlen($state) > 64)) {
            throw new \InvalidArgumentException('invalid length for $state when calling RentalCarLocation., must be smaller than or equal to 64.');
        }
        if (!is_null($state) && (strlen($state) < 2)) {
            throw new \InvalidArgumentException('invalid length for $state when calling RentalCarLocation., must be bigger than or equal to 2.');
        }

        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets branchName
     * @return string
     */
    public function getBranchName()
    {
        return $this->container['branchName'];
    }

    /**
     * Sets branchName
     * @param string $branchName Internal name used to identify rental company branch.
     * @return $this
     */
    public function setBranchName($branchName)
    {
        if (!is_null($branchName) && (strlen($branchName) > 64)) {
            throw new \InvalidArgumentException('invalid length for $branchName when calling RentalCarLocation., must be smaller than or equal to 64.');
        }
        if (!is_null($branchName) && (strlen($branchName) < 2)) {
            throw new \InvalidArgumentException('invalid length for $branchName when calling RentalCarLocation., must be bigger than or equal to 2.');
        }

        $this->container['branchName'] = $branchName;

        return $this;
    }

    /**
     * Gets country
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     * @param string $country Country of the rental car company branch.
     * @return $this
     */
    public function setCountry($country)
    {
        if (!is_null($country) && (strlen($country) > 64)) {
            throw new \InvalidArgumentException('invalid length for $country when calling RentalCarLocation., must be smaller than or equal to 64.');
        }
        if (!is_null($country) && (strlen($country) < 2)) {
            throw new \InvalidArgumentException('invalid length for $country when calling RentalCarLocation., must be bigger than or equal to 2.');
        }

        $this->container['country'] = $country;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\BrightWrite\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\BrightWrite\ObjectSerializer::sanitizeForSerialization($this));
    }
}
