<?php
/**
 * PartnerApi
 * PHP version 5
 *
 * @category Class
 * @package  BrightWrite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BrightWrite™
 *
 * BrightWrite API
 *
 * OpenAPI spec version: 0.1.7
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BrightWrite\Api;

use \BrightWrite\ApiClient;
use \BrightWrite\ApiException;
use \BrightWrite\Configuration;
use \BrightWrite\ObjectSerializer;

/**
 * PartnerApi Class Doc Comment
 *
 * @category Class
 * @package  BrightWrite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PartnerApi
{
    /**
     * API Client
     *
     * @var \BrightWrite\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \BrightWrite\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\BrightWrite\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \BrightWrite\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \BrightWrite\ApiClient $apiClient set the API client
     *
     * @return PartnerApi
     */
    public function setApiClient(\BrightWrite\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation brightwriteControllerPricingRequestCarRentalAction
     *
     * Pricing request for a car rental policy
     *
     * @param \BrightWrite\Model\PricingRequestCarRental $pricingRequest Pricing request should contain information about quoted policy and related booking information (required)
     * @throws \BrightWrite\ApiException on non-2xx response
     * @return \BrightWrite\Model\PricingResponse
     */
    public function brightwriteControllerPricingRequestCarRentalAction($pricingRequest)
    {
        list($response) = $this->brightwriteControllerPricingRequestCarRentalActionWithHttpInfo($pricingRequest);
        return $response;
    }

    /**
     * Operation brightwriteControllerPricingRequestCarRentalActionWithHttpInfo
     *
     * Pricing request for a car rental policy
     *
     * @param \BrightWrite\Model\PricingRequestCarRental $pricingRequest Pricing request should contain information about quoted policy and related booking information (required)
     * @throws \BrightWrite\ApiException on non-2xx response
     * @return array of \BrightWrite\Model\PricingResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function brightwriteControllerPricingRequestCarRentalActionWithHttpInfo($pricingRequest)
    {
        // verify the required parameter 'pricingRequest' is set
        if ($pricingRequest === null) {
            throw new \InvalidArgumentException('Missing the required parameter $pricingRequest when calling brightwriteControllerPricingRequestCarRentalAction');
        }
        // parse inputs
        $resourcePath = "/pricingRequestCarRental";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // body params
        $_tempBody = null;
        if (isset($pricingRequest)) {
            $_tempBody = $pricingRequest;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('x-api-key');
        if (strlen($apiKey) !== 0) {
            $headerParams['x-api-key'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\BrightWrite\Model\PricingResponse',
                '/pricingRequestCarRental'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\BrightWrite\Model\PricingResponse', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\BrightWrite\Model\PricingResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation brightwriteControllerQuoteConversionAction
     *
     * Pricing request for car rental business
     *
     * @param \BrightWrite\Model\QuoteConversion $conversion QuoteConversion (required)
     * @throws \BrightWrite\ApiException on non-2xx response
     * @return void
     */
    public function brightwriteControllerQuoteConversionAction($conversion)
    {
        list($response) = $this->brightwriteControllerQuoteConversionActionWithHttpInfo($conversion);
        return $response;
    }

    /**
     * Operation brightwriteControllerQuoteConversionActionWithHttpInfo
     *
     * Pricing request for car rental business
     *
     * @param \BrightWrite\Model\QuoteConversion $conversion QuoteConversion (required)
     * @throws \BrightWrite\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function brightwriteControllerQuoteConversionActionWithHttpInfo($conversion)
    {
        // verify the required parameter 'conversion' is set
        if ($conversion === null) {
            throw new \InvalidArgumentException('Missing the required parameter $conversion when calling brightwriteControllerQuoteConversionAction');
        }
        // parse inputs
        $resourcePath = "/quoteConversion";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // body params
        $_tempBody = null;
        if (isset($conversion)) {
            $_tempBody = $conversion;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('x-api-key');
        if (strlen($apiKey) !== 0) {
            $headerParams['x-api-key'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/quoteConversion'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }
}
