<?php
/**
 * BookingRentalCarTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightWrite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BrightWrite™
 *
 * BrightWrite API
 *
 * OpenAPI spec version: 0.1.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BrightWrite;

/**
 * BookingRentalCarTest Class Doc Comment
 *
 * @category    Class */
// * @description BookingRentalCar
/**
 * @package     BrightWrite
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BookingRentalCarTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BookingRentalCar"
     */
    public function testBookingRentalCar()
    {
    }

    /**
     * Test attribute "rentalCarBookingId"
     */
    public function testPropertyRentalCarBookingId()
    {
    }

    /**
     * Test attribute "dropOffLocation"
     */
    public function testPropertyDropOffLocation()
    {
    }

    /**
     * Test attribute "pickUpLocation"
     */
    public function testPropertyPickUpLocation()
    {
    }

    /**
     * Test attribute "subtotalPrice"
     */
    public function testPropertySubtotalPrice()
    {
    }

    /**
     * Test attribute "taxesAndFees"
     */
    public function testPropertyTaxesAndFees()
    {
    }

    /**
     * Test attribute "totalPrice"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "priceCurrency"
     */
    public function testPropertyPriceCurrency()
    {
    }

    /**
     * Test attribute "pickupDateTime"
     */
    public function testPropertyPickupDateTime()
    {
    }

    /**
     * Test attribute "dropOffDateTime"
     */
    public function testPropertyDropOffDateTime()
    {
    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {
    }

    /**
     * Test attribute "driverCount"
     */
    public function testPropertyDriverCount()
    {
    }

    /**
     * Test attribute "toddlerSeatCount"
     */
    public function testPropertyToddlerSeatCount()
    {
    }

    /**
     * Test attribute "infantChildSeatCount"
     */
    public function testPropertyInfantChildSeatCount()
    {
    }

    /**
     * Test attribute "sIPPCode"
     */
    public function testPropertySIPPCode()
    {
    }

    /**
     * Test attribute "vehicleType"
     */
    public function testPropertyVehicleType()
    {
    }
}
