<?php
/**
 * PricingRequestCarRentalTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightWrite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BrightWrite™
 *
 * BrightWrite API
 *
 * OpenAPI spec version: 0.1.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BrightWrite;

/**
 * PricingRequestCarRentalTest Class Doc Comment
 *
 * @category    Class */
// * @description PricingRequestCarRental
/**
 * @package     BrightWrite
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PricingRequestCarRentalTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PricingRequestCarRental"
     */
    public function testPricingRequestCarRental()
    {
    }

    /**
     * Test attribute "partnerPrimaryInsuredId"
     */
    public function testPropertyPartnerPrimaryInsuredId()
    {
    }

    /**
     * Test attribute "partnerQuoteId"
     */
    public function testPropertyPartnerQuoteId()
    {
    }

    /**
     * Test attribute "effectiveDateTime"
     */
    public function testPropertyEffectiveDateTime()
    {
    }

    /**
     * Test attribute "requestDateTime"
     */
    public function testPropertyRequestDateTime()
    {
    }

    /**
     * Test attribute "expirationDateTime"
     */
    public function testPropertyExpirationDateTime()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "insuredPersons"
     */
    public function testPropertyInsuredPersons()
    {
    }

    /**
     * Test attribute "partnerId"
     */
    public function testPropertyPartnerId()
    {
    }

    /**
     * Test attribute "pricingRequestOrigin"
     */
    public function testPropertyPricingRequestOrigin()
    {
    }

    /**
     * Test attribute "partnerPrice"
     */
    public function testPropertyPartnerPrice()
    {
    }

    /**
     * Test attribute "appId"
     */
    public function testPropertyAppId()
    {
    }

    /**
     * Test attribute "appEnv"
     */
    public function testPropertyAppEnv()
    {
    }

    /**
     * Test attribute "purchaser"
     */
    public function testPropertyPurchaser()
    {
    }

    /**
     * Test attribute "brightwriteCookieId"
     */
    public function testPropertyBrightwriteCookieId()
    {
    }

    /**
     * Test attribute "policyDestinationCountryCode"
     */
    public function testPropertyPolicyDestinationCountryCode()
    {
    }

    /**
     * Test attribute "policyType"
     */
    public function testPropertyPolicyType()
    {
    }

    /**
     * Test attribute "requestedLiability"
     */
    public function testPropertyRequestedLiability()
    {
    }

    /**
     * Test attribute "policyExcess"
     */
    public function testPropertyPolicyExcess()
    {
    }

    /**
     * Test attribute "policyLiability"
     */
    public function testPropertyPolicyLiability()
    {
    }

    /**
     * Test attribute "currencyForExcessAndLiability"
     */
    public function testPropertyCurrencyForExcessAndLiability()
    {
    }

    /**
     * Test attribute "rentalCarBooking"
     */
    public function testPropertyRentalCarBooking()
    {
    }
}
