<?php
/**
 * PricingResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightWrite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BrightWrite™
 *
 * BrightWrite API
 *
 * OpenAPI spec version: 0.1.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BrightWrite;

/**
 * PricingResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description PricingResponse
/**
 * @package     BrightWrite
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PricingResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PricingResponse"
     */
    public function testPricingResponse()
    {
    }

    /**
     * Test attribute "partnerId"
     */
    public function testPropertyPartnerId()
    {
    }

    /**
     * Test attribute "pricingRequestId"
     */
    public function testPropertyPricingRequestId()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "segment"
     */
    public function testPropertySegment()
    {
    }

    /**
     * Test attribute "pricingRule"
     */
    public function testPropertyPricingRule()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "modifier"
     */
    public function testPropertyModifier()
    {
    }
}
