<?php
/**
 * QuoteConversionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightWrite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BrightWrite™
 *
 * BrightWrite API
 *
 * OpenAPI spec version: 0.1.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BrightWrite;

/**
 * QuoteConversionTest Class Doc Comment
 *
 * @category    Class */
// * @description QuoteConversion
/**
 * @package     BrightWrite
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteConversionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QuoteConversion"
     */
    public function testQuoteConversion()
    {
    }

    /**
     * Test attribute "partnerQuoteId"
     */
    public function testPropertyPartnerQuoteId()
    {
    }

    /**
     * Test attribute "pricingRequestId"
     */
    public function testPropertyPricingRequestId()
    {
    }

    /**
     * Test attribute "purchaser"
     */
    public function testPropertyPurchaser()
    {
    }

    /**
     * Test attribute "rentalCarBooking"
     */
    public function testPropertyRentalCarBooking()
    {
    }
}
