<?php
/**
 * PartnerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BrightWrite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BrightWrite™
 *
 * BrightWrite API
 *
 * OpenAPI spec version: 0.1.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BrightWrite;

use \BrightWrite\Configuration;
use \BrightWrite\ApiClient;
use \BrightWrite\ApiException;
use \BrightWrite\ObjectSerializer;

/**
 * PartnerApiTest Class Doc Comment
 *
 * @category Class
 * @package  BrightWrite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PartnerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for brightwriteControllerPricingRequestCarRentalAction
     *
     * Pricing request for a car rental policy.
     *
     */
    public function testBrightwriteControllerPricingRequestCarRentalAction()
    {
    }

    /**
     * Test case for brightwriteControllerQuoteConversionAction
     *
     * Pricing request for car rental business.
     *
     */
    public function testBrightwriteControllerQuoteConversionAction()
    {
    }
}
