<?php
/**
 * BookingRentalCarTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightWrite
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BrightWrite™
 *
 * BrightWrite API
 *
 * OpenAPI spec version: 0.1.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BrightWrite;

/**
 * BookingRentalCarTest Class Doc Comment
 *
 * @category    Class */
// * @description BookingRentalCar
/**
 * @package     BrightWrite
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BookingRentalCarTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "BookingRentalCar"
     */
    public function testBookingRentalCar()
    {

    }

    /**
     * Test attribute "totalPrice"
     */
    public function testPropertyTotalPrice()
    {

    }

    /**
     * Test attribute "dropOffLocation"
     */
    public function testPropertyDropOffLocation()
    {

    }

    /**
     * Test attribute "priceCurrency"
     */
    public function testPropertyPriceCurrency()
    {

    }

    /**
     * Test attribute "pickupLocation"
     */
    public function testPropertyPickupLocation()
    {

    }

    /**
     * Test attribute "taxesAndFees"
     */
    public function testPropertyTaxesAndFees()
    {

    }

    /**
     * Test attribute "subtotalPrice"
     */
    public function testPropertySubtotalPrice()
    {

    }

    /**
     * Test attribute "pickupDateTime"
     */
    public function testPropertyPickupDateTime()
    {

    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {

    }

    /**
     * Test attribute "dropOffDateTime"
     */
    public function testPropertyDropOffDateTime()
    {

    }

    /**
     * Test attribute "toddlerSeatCount"
     */
    public function testPropertyToddlerSeatCount()
    {

    }

    /**
     * Test attribute "driverCount"
     */
    public function testPropertyDriverCount()
    {

    }

    /**
     * Test attribute "infantChildSeatCount"
     */
    public function testPropertyInfantChildSeatCount()
    {

    }

    /**
     * Test attribute "sIPPCode"
     */
    public function testPropertySIPPCode()
    {

    }

    /**
     * Test attribute "rentalCarBookingID"
     */
    public function testPropertyRentalCarBookingID()
    {

    }

}
